---
title: "BRMS univariate models"
author: "Sam Straus and Melissa Guzman"
date: "12/04/2023"
output: html_document
---

```{r}
library(brms)
library(stringr)
library(dplyr)
library(rstan)

### load traits
traits_phylo <- read.csv("../data/Traits_final_cleaned.csv", fileEncoding="latin1")

traits_phylo$diet_broadest_cat <- as.factor(traits_phylo$diet_broadest_cat)
traits_phylo$diet_broadest_cat <- droplevels(traits_phylo$diet_broadest_cat)
levels(traits_phylo$diet_broadest_cat)

## remove eland because source is missing!
traits_phylo <- traits_phylo[-which(traits_phylo$scientific_name.x=='Tragelaphus_oryx'),]

```

Trophic guild, random slope and intercept, include year

```{r guild-univariate-year}
bf_dispersal_trophic_withyear <- bf(dispersal_km ~ log(Mass_kg) + (log(Mass_kg)|diet_broadest_cat) + dispersal_year) + lognormal(link = "identity")
bf_home_range_trophic_withyear <- bf(hr.radius ~ log(Mass_kg)+ (log(Mass_kg)|diet_broadest_cat) + foraging_year) + lognormal(link = "identity")
bf_migration_trophic_withyear <- bf(Migration_km ~ log(Mass_kg) + (log(Mass_kg)|diet_broadest_cat) + migration_year) + hurdle_lognormal(link = 'identity')


trophic_year_prior_disp <- prior(normal(0,5),class = 'b', coef = logMass_kg) +
  prior(normal(0,5),class = 'b', coef = dispersal_year) +
  prior(student_t(5, 0, 3), class = 'Intercept') +
  prior(student_t(6, 0, 2.9), class = 'sd') +
  prior(student_t(5, 0, 2.9), class = 'sigma')

## works
trophic.disp_withyear <- brm(bf_dispersal_trophic_withyear, data = traits_phylo, 
                          control = list(adapt_delta = 0.995, max_treedepth=20), 
                          iter = 5000, cores = 16,
                          prior = trophic_year_prior_disp)

trophic_year_prior_for <- prior(normal(0,5),class = 'b', coef = logMass_kg) +
  prior(normal(0,5),class = 'b', coef = foraging_year) +
  prior(student_t(5, 0, 3), class = 'Intercept') +
  prior(student_t(6, 0, 2.9), class = 'sd') +
  prior(student_t(5, 0, 2.9), class = 'sigma')

# works
trophic.for_withyear <- brm(bf_home_range_trophic_withyear, data = traits_phylo, 
                         control = list(adapt_delta = 0.995, max_treedepth=20), iter = 5000, cores = 16,
                         prior = trophic_year_prior_for)


## works
trophic_year_prior_mig <- prior(normal(0,3),class = 'b', coef = logMass_kg) +
  prior(normal(0,3),class = 'b', coef = migration_year) +
  prior(student_t(5, 0, 3), class = 'Intercept') +
  prior(student_t(4, 0, 2.9), class = 'sd') +
  prior(student_t(4, 0, 2.9), class = 'sigma') 


trophic.mig_withyear <- brm(bf_migration_trophic_withyear, data = traits_phylo, 
                         control = list(adapt_delta = 0.995, max_treedepth=20), iter = 4000, cores = 16,
                         prior = trophic_year_prior_mig)


```

```{r save-guild-mods}

saveRDS(trophic.disp_withyear, "../mods/trophic.disp_withyear.rds")
saveRDS(trophic.for_withyear, "../mods/trophic.for_withyear.rds")
saveRDS(trophic.mig_withyear, "../mods/trophic.mig_withyear.rds") 

```


Trophic guild, mulivariate with year
```{r trophic-multivar-year}

trophic_withyear_prior_multivar <- prior(normal(0,5), class = 'b', 
                              coef = logMass_kg, resp = "dispersalkm") +
  prior(normal(0,5),class = 'b', coef = dispersal_year, resp = "dispersalkm") +
  prior(student_t(6, 0, 2.9), class = 'sd', resp = "dispersalkm") +
  prior(student_t(5, 0, 2.9), class = 'sigma', resp = "dispersalkm")+
  prior(normal(0,5), class = 'b', coef = logMass_kg, resp = "hrradius") +
  prior(normal(0,5),class = 'b', coef = foraging_year, resp = 'hrradius') +
  prior(student_t(6, 0, 2.9), class = 'sd', resp = "hrradius") +
  prior(student_t(5, 0, 2.9), class = 'sigma', resp = "hrradius") +
  prior(normal(0,7), class = 'b', coef = logMass_kg, resp = "Migrationkm") +
  prior(normal(0,7),class = 'b', coef = migration_year, resp = "Migrationkm") +
  prior(student_t(5, 0, 3), class = 'Intercept', resp = "Migrationkm") +
  prior(student_t(4, 0, 2.9), class = 'sd', resp = "Migrationkm") +
  prior(student_t(4, 0, 2.9), class = 'sigma',resp = "Migrationkm")

trophic_multivar_withyear <- brm(bf_dispersal_trophic_withyear + bf_home_range_trophic_withyear +
    bf_migration_trophic_withyear, data = traits_phylo, 
    control = list(adapt_delta = 0.995, max_treedepth = 20), 
    iter = 7000, cores = 16, prior = trophic_withyear_prior_multivar)


 saveRDS(trophic_multivar_withyear, "../mods/trophic_multivar_withyear.rds")


```


Class, Univariate, Random intercept and slope, with year
```{r univariate-class-withyear}

# random slope, with year
bf_dispersal_class_withyear <- bf(dispersal_km ~ log(Mass_kg) + 
                      (log(Mass_kg)|p|class) + dispersal_year) + lognormal()
bf_home_range_class_withyear <- bf(hr.radius ~ log(Mass_kg)+ 
                      (log(Mass_kg)|p|class) + foraging_year) +  lognormal()
bf_migration_class_withyear <- bf(Migration_km ~ log(Mass_kg) + 
                      (log(Mass_kg)|p|class) + migration_year) + hurdle_lognormal()

class_withyear_prior <- prior(normal(0,5),class = 'b', coef = logMass_kg) +
  prior(student_t(4, 0, 4), class = 'Intercept') +
  prior(student_t(6, 0, 2.9), class = 'sd') +
  prior(student_t(4, 0, 2.9), class = 'sigma')

class.disp_withyear <- brm(bf_dispersal_class_withyear, data = traits_phylo, 
                         control = list(adapt_delta = 0.995, max_treedepth=20), 
                         iter = 3000, cores = 4, prior = class_withyear_prior)


class.for_withyear <- brm(bf_home_range_class_withyear, data = traits_phylo, 
                        control = list(adapt_delta = 0.995, max_treedepth=20), 
                        iter = 3000, cores = 4, prior = class_withyear_prior)



class.mig_withyear <- brm(bf_migration_class_withyear, data = traits_phylo, 
                        control = list(adapt_delta = 0.995, max_treedepth=20), 
                        iter = 3000, cores = 4, prior = class_withyear_prior)

```
Save rds files
```{r}
saveRDS(class.disp_withyear, "../mods/class.disp_withyear.rds")
saveRDS(class.for_withyear, "../mods/class.for_withyear.rds")
saveRDS(class.mig_withyear, "../mods/class.mig_withyear.rds")

```


Class, but multivariate
```{r multivariate-class-withyear}

class_withyear_prior_multivar <- prior(normal(0,5), class = 'b', 
                              coef = logMass_kg, resp = "dispersalkm") +
  prior(student_t(4, 0, 4), class = 'Intercept', resp = "dispersalkm") +
  prior(student_t(6, 0, 2.9), class = 'sd', resp = "dispersalkm") +
  prior(student_t(4, 0, 2.9), class = 'sigma', resp = "dispersalkm")+
  prior(normal(0,5), class = 'b', coef = logMass_kg, resp = "hrradius") +
  prior(student_t(4, 0, 4), class = 'Intercept', resp = "hrradius") +
  prior(student_t(6, 0, 2.9), class = 'sd', resp = "hrradius") +
  prior(student_t(4, 0, 2.9), class = 'sigma', resp = "hrradius") +
  prior(normal(0,5), class = 'b', coef = logMass_kg, resp = "Migrationkm") +
  prior(student_t(4, 0, 4), class = 'Intercept', resp = "Migrationkm") +
  prior(student_t(6, 0, 2.9), class = 'sd', resp = "Migrationkm") +
  prior(student_t(4, 0, 2.9), class = 'sigma',resp = "Migrationkm")

class_multivar <- brm(bf_dispersal_class_withyear + bf_home_range_class_withyear +
    bf_migration_class_withyear, data = traits_phylo, 
    control = list(adapt_delta = 0.995, max_treedepth = 20), 
    iter = 4000, cores = 16, prior = class_withyear_prior_multivar)

saveRDS(class_multivar, "../mods/class_multivar_withyear.rds")

````